### ISSUE TITLE
Python结束后浏览器相关进程仍在运行

### ISSUE THREAD

**Issue by Steven-Zhl** [GeorgeHu6/tex-converter#1]
## 问题描述：

* 我使用PyCharm修改源代码，但在每次调试结束时PyCharm总是提示“等待分离线程”。
* 起初我并没有在意，直接强行终止Python再进行调试。但过段时间后，我打开任务管理器时发现了许多"chromedriver.exe"和"Google Chrome"仍在后台运行(如下图)，但我并未直接启动过Chrome浏览器。

![image](https://github.com/GeorgeHu6/tex-converter/assets/80385790/fbfc0176-e749-4a96-bc19-6ad5943ff472)

* 这是个比较明显的Bug，我猜测这些进程是由于selenium或WebDriver未手动结束而残留的，我会尝试修复这个问题。

## 测试环境：

* Python 3.11.5 (Anaconda)
  * selenium 4.15.2
  * urllib3 2.0.7
* Chrome 119.0.6045.124

## 能否复现：

* 是，但我只在Chrome浏览器中测试过，Firefox和Edge不清楚

**Comment by GeorgeHu6** [comment]
## 复现与排查

经测试，成功在PyChram的调试中进行了现象的复现，并且此现象可能会把PyCharm整个卡死。另外，使用PyCharm进行运行时也有一定概率会出现这样的问题；使用VSCode进行运行和调试完全不会出现这种问题；使用命令行直接运行也不会出现这种问题。

其次还观察到在此现象发生时，chromedriver进程是作为PyCharm的子进程出现的，而不是作为Python的子进程出现的。

## 问题原因

在正常情况下，chromedriver应作为Python的子进程出现，同时受其自动管理。但由于PyCharm调试时的一些进程管理策略，当chromedriver作为PyCharm的子进程出现时，Python将无法自动管理chromedriver。

## 解决方案

添加退出窗口时关闭chromedriver的相关代码，但这会导致退出时卡顿，等待后续引入多线程机制进行解决。
